on: [push]

jobs:
  build_docs_job:
    if: (github.repository == 'DavidLeoni/sps') && ((github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/dev'))
    runs-on: ubuntu-18.04
    name: Build docs    
    steps:   
    - name: Install deps
      run: |
        sudo apt-get install tree
    - name: sets environment 
      run: |        
        echo "GIT_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
        echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
        echo "LANGUAGE=it" >> $GITHUB_ENV
    - name: apply docs version renaming
      if: env.GIT_TAG == 'master'
      run: echo "VERSION=latest" >> $GITHUB_ENV
    - name: sets WEB_PATH
      run: echo "WEB_PATH=" >> $GITHUB_ENV
    - name: Run Sphinx in RTD docker      
      uses: DavidLeoni/readthedocs-to-actions@v1.2
      with:
        RTD_PRJ_NAME: sps
        GIT_URL: https://github.com/${{ github.repository }}.git
        GIT_TAG: ${{ env.GIT_TAG }}
        VERSION: ${{ env.VERSION }}
        REQUIREMENTS: requirements-build.txt
        LANGUAGE: ${{ env.LANGUAGE }}
        RTD_HTML_SINGLE: false
        RTD_HTML_EXT: false      
        GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
    - name: Show workspace output
      run: |        
        tree -aC $GITHUB_WORKSPACE
    - name: Commit documentation changes
      run: |
        git clone --depth 1 --branch sps.davidleoni.it https://github.com/${{ github.repository }}.git sps.davidleoni.it        
        
        mkdir -p sps.davidleoni.it/${{ env.WEB_PATH }}
        cp -r $GITHUB_WORKSPACE/html/* sps.davidleoni.it/${{ env.WEB_PATH }}
        if compgen -G "$GITHUB_WORKSPACE/latex/*.pdf" > /dev/null; then
             cp -r $GITHUB_WORKSPACE/latex/*.pdf sps.davidleoni.it/${{ env.WEB_PATH }}
        else
             echo "ERROR: NO PDF FILES WHERE GENERATED!"
        fi
        if compgen -G "$GITHUB_WORKSPACE/epub/*.epub" > /dev/null; then
             cp -r $GITHUB_WORKSPACE/epub/*.epub sps.davidleoni.it/${{ env.WEB_PATH }}
        else
             echo "ERROR: NO EPUB FILES WHERE GENERATED!"
        fi
        # note: html zip is already provided by Github
        cd sps.davidleoni.it        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .      
        touch .nojekyll
        git add .nojekyll  # explicit, otherwise is ignored
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: sps.davidleoni.it
        directory: sps.davidleoni.it
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: update server
      run: |
        curl --silent --digest --user ${{ secrets.DAVAPI_CREDENTIALS}} ${{ secrets.DAVAPI_URL }}    